name: Update ticket tally

on:
  schedule:
    - cron: "*/5 * * * *"  # Updates ticket tally every 5 minutes
  workflow_dispatch:

on:
  workflow_dispatch:

# Allows the workflow to update files and push changes
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: python -m pip install --upgrade pip

# Allows python modules to load correctly
      - run: pip install -r requirements.txt

      - run: python process.py

# Commits the updated ticket balance files back to the repository
      - name: Commit updated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/ticket_balance.txt
          git add data/ticket_balance.json
          git commit -m "Update ticket balance files" || exit 0
          git push